from __future__ import annotations

import os
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# ไฟล์ SQLite เดิมก่อนย้ายไป Supabase เก็บไว้เป็นข้อมูลสำรอง และเป็นต้นทางของ scripts/migrate_sqlite_to_supabase.py
SQLITE_BACKUP_PATH = BASE_DIR / "pattaya_tourism.db"

# ปิด prepared statement ฝั่งเซิร์ฟเวอร์ เพื่อให้ใช้ได้ทั้ง Session pooler (5432) และ Transaction pooler (6543) ของ Supabase
CONNECTION_OPTIONS = {"row_factory": dict_row, "prepare_threshold": None}

_pool: ConnectionPool | None = None


def database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError(
            "ไม่พบ DATABASE_URL: สร้างไฟล์ .env ที่รากโปรเจกต์ แล้วใส่ connection string แบบ Session pooler ของ Supabase"
        )
    return url


def connect() -> psycopg.Connection:
    """connection เดี่ยวสำหรับสคริปต์ ใช้กับ with: จบบล็อกปกติจะ commit ถ้าเกิด exception จะ rollback ทั้งหมด"""
    return psycopg.connect(database_url(), **CONNECTION_OPTIONS)


def get_pool() -> ConnectionPool:
    """pool สำหรับเว็บเซิร์ฟเวอร์ ฐานข้อมูลอยู่บนคลาวด์ ถ้าเปิด connection ใหม่ทุก query จะช้ามาก"""
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            database_url(),
            min_size=1,
            max_size=5,
            # เว็บอ่านข้อมูลอย่างเดียว ใช้ autocommit ไม่ต้องส่ง BEGIN/COMMIT ไปกลับคลาวด์เพิ่มทุก query
            kwargs={**CONNECTION_OPTIONS, "autocommit": True},
            open=True,
        )
    return _pool


def close_pool() -> None:
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None


# เรียงตาม foreign key (ตารางแม่มาก่อนตารางลูก) สคริปต์ย้ายข้อมูลใช้ลำดับนี้ด้วย
TABLES = (
    "raw_excel_cells",
    "pattaya_report_metrics",
    "tourism_monthly",
    "zone_traffic_volume",
    "demographic_profiles",
    "data_sources",
    "imports",
    "import_errors",
    "poi_businesses",
    "roles",
    "users",
    "user_roles",
    "role_permissions",
    "public_holidays",
    "weather_daily",
    "audit_logs",
)

SCHEMA = """
CREATE TABLE IF NOT EXISTS raw_excel_cells (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT NOT NULL,
    sheet_name TEXT NOT NULL,
    row_number INTEGER NOT NULL,
    column_number INTEGER NOT NULL,
    cell_value TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_raw_excel_sheet
    ON raw_excel_cells (source_file, sheet_name);
CREATE TABLE IF NOT EXISTS pattaya_report_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT NOT NULL,
    sheet_name TEXT NOT NULL,
    metric_label TEXT NOT NULL,
    metric_value DOUBLE PRECISION,
    unit TEXT,
    year INTEGER,
    quarter INTEGER,
    source_row INTEGER,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_report_metric_label
    ON pattaya_report_metrics (metric_label);
CREATE TABLE IF NOT EXISTS tourism_monthly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT NOT NULL,
    location TEXT NOT NULL,
    calendar_year_be INTEGER NOT NULL,
    calendar_year INTEGER NOT NULL,
    month_id INTEGER NOT NULL,
    month_name TEXT,
    number_of_tourists INTEGER NOT NULL,
    unit TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(source_file, location, calendar_year_be, month_id)
);
CREATE INDEX IF NOT EXISTS idx_tourism_monthly_date
    ON tourism_monthly (calendar_year, month_id);
CREATE TABLE IF NOT EXISTS zone_traffic_volume (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT NOT NULL,
    intersection_id TEXT NOT NULL,
    intersection_name TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    calendar_year_be INTEGER NOT NULL,
    calendar_year INTEGER NOT NULL,
    month_id INTEGER NOT NULL,
    month_name TEXT,
    vehicle_volume INTEGER NOT NULL,
    unit TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- ที่มาของพิกัด: osm_junction_name = โหนดแยกที่มีชื่อตรงใน OSM,
    -- osm_road_pair = จุดที่ถนนสองสายตัดกันใน OSM, NULL = ยังไม่มีพิกัด
    geocode_method TEXT,
    geocode_detail TEXT,
    UNIQUE(source_file, intersection_id, calendar_year_be, month_id)
);
CREATE INDEX IF NOT EXISTS idx_zone_traffic_date
    ON zone_traffic_volume (calendar_year, month_id);
CREATE INDEX IF NOT EXISTS idx_zone_traffic_intersection
    ON zone_traffic_volume (intersection_name);
CREATE TABLE IF NOT EXISTS demographic_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT NOT NULL,
    location TEXT NOT NULL,
    calendar_year_be INTEGER NOT NULL,
    calendar_year INTEGER NOT NULL,
    category TEXT NOT NULL,
    segment TEXT NOT NULL,
    population INTEGER NOT NULL,
    unit TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(source_file, location, calendar_year_be, category, segment)
);
CREATE INDEX IF NOT EXISTS idx_demographic_year
    ON demographic_profiles (calendar_year, category);
-- Data provenance and import tracking
CREATE TABLE IF NOT EXISTS data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    source_type TEXT NOT NULL, -- e.g. open_api, csv, weather, holidays
    endpoint TEXT,
    metadata TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id BIGINT REFERENCES data_sources(id),
    import_type TEXT NOT NULL, -- csv | api
    source_name TEXT,
    raw_filename TEXT,
    source_url TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    records_total INTEGER,
    records_success INTEGER,
    records_failed INTEGER,
    notes TEXT
);
CREATE TABLE IF NOT EXISTS import_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL REFERENCES imports(id),
    row_number INTEGER,
    error_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- POI / Businesses
CREATE TABLE IF NOT EXISTS poi_businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id BIGINT REFERENCES data_sources(id),
    external_id TEXT,
    name TEXT NOT NULL,
    category TEXT,
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    phone TEXT,
    website TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(data_source_id, external_id)
);
CREATE INDEX IF NOT EXISTS idx_poi_location ON poi_businesses (latitude, longitude);
-- User and RBAC
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT
);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    full_name TEXT,
    email TEXT UNIQUE,
    password_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id),
    permission TEXT NOT NULL,
    PRIMARY KEY (role_id, permission)
);
-- Public holidays and festivals
CREATE TABLE IF NOT EXISTS public_holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id BIGINT REFERENCES data_sources(id),
    date DATE NOT NULL,
    name TEXT NOT NULL,
    local_name TEXT,
    holiday_type TEXT,
    country_code TEXT NOT NULL DEFAULT 'TH',
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(date, name, country_code)
);
CREATE INDEX IF NOT EXISTS idx_public_holidays_date ON public_holidays (date);
-- Historical daily weather (Open-Meteo Archive) ใช้วิเคราะห์ผลกระทบของฝนย้อนหลัง
-- ต่างจาก /api/weather/* ที่เรียกสดและไม่เก็บลงฐานข้อมูล
CREATE TABLE IF NOT EXISTS weather_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id BIGINT REFERENCES data_sources(id),
    date DATE NOT NULL UNIQUE,
    precipitation_mm DOUBLE PRECISION,
    precipitation_hours DOUBLE PRECISION,
    temperature_max_c DOUBLE PRECISION,
    temperature_min_c DOUBLE PRECISION,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Audit logs for imports, user actions
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    actor TEXT,
    target TEXT,
    details TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""

# Supabase เปิดทุกตารางใน schema public ให้เรียกผ่าน REST API ด้วย anon key ได้ ถ้าไม่เปิด RLS
# ใครที่ได้ anon key ไปก็อ่าน/แก้ข้อมูลได้ เปิด RLS โดยไม่มี policy = ปิดทาง REST API ทั้งหมด
# ส่วนแอปนี้ต่อด้วยสิทธิ์เจ้าของตาราง (postgres) ซึ่งไม่ถูก RLS บังคับ จึงใช้งานได้ตามปกติ
ENABLE_ROW_LEVEL_SECURITY = "".join(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;\n" for table in TABLES)


def initialize_database() -> None:
    with connect() as connection:
        connection.execute(SCHEMA + ENABLE_ROW_LEVEL_SECURITY)
